name: flutter_app_badger_plus
description: Plugin to update the app badge on the launcher (both for Android, iOS and macOS)
version: 1.0.0
homepage: https://github.com/g123k/flutter_app_badger_plus

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fr.g123k.flutterappbadgerplus
        pluginClass: FlutterAppBadgerPlusPlugin
      ios:
        pluginClass: FlutterAppBadgerPlusPlugin
      macos:
        pluginClass: FlutterAppBadgerPlusPlugin


environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.10.0"
